server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secret: your-secret-key-here-must-be-at-least-256-bits-long
  expiration: 86400000 # 24 hours

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.capstone: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cors:
  allowed-origins: https://web-server-281506025529.asia-northeast3.run.app